version: "3"

networks:
  cube-net:
    external: false

services:
  # mssql-server:
  #   container_name: mssql-server
  #   # image: mcr.microsoft.com/mssql/server:2022-latest
  #   build:
  #     context: ./mssql
  #     dockerfile: Dockerfile
  #   healthcheck:
  #     test: ["CMD", "sqlcmd", "-q", "SELECT 1"]
  #     interval: 5s
  #     timeout: 2s
  #     retries: 15
  #   networks:
  #     - cube-net
  #   ports:
  #     - "1433:1433"
  #   restart: on-failure:3

  mysql-server:
    container_name: mysql-server
    build:
      context: ./starrocks
      dockerfile: Dockerfile
    # healthcheck:
    #   test: ["CMD", "sqlcmd", "-q", "SELECT 1"]
    #   interval: 5s
    #   timeout: 2s
    #   retries: 15
    networks:
      - cube-net
    ports:
      - "9030:9030"
      - "8030:8030"
      - "8040:8040"
    restart: on-failure:3
    dns:
      - 8.8.8.8
      - 4.4.4.4

  migrations:
    container_name: migrations
    build:
      context: ./migration
      dockerfile: Dockerfile
    environment:
      - DBHOST=mysql-server
      - DBPORT=9030
    networks:
      - cube-net
    dns:
      - 8.8.8.8
      - 4.4.4.4

  cube:
    container_name: cube
    image: cubejs/cube:latest
    depends_on:
      - mysql-server
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    networks:
      - cube-net
    volumes:
      - ./.env:/cube/conf/.env
      - ./model:/cube/conf/model:ro
    restart: on-failure:3
